# @name get-prompts

GET http://localhost:3001/prompts

###

# @name upload

POST http://localhost:3001/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="CainaAudio.mp3"
Content-Type: audio/mpeg

< ./CainaAudio.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3001/videos/d21913a2-daa0-46c9-b470-c46498b1aa8f/transcription
Content-Type: application/json

{
  "prompt": "interface"
}

###

# @name generate_AI_completion
POST http://localhost:3001/ai/generate
Content-Type: application/json

{
  "videoId": "d21913a2-daa0-46c9-b470-c46498b1aa8f",
  "prompt": "Gere um resumo sicinto",
  "temperature": 0.5
}